# nonk8s
apiVersion: "backstage.io/v1alpha1"
kind: "Component"
metadata:
  name: "retningslinjer-fagomrade-produktspesifikasjon"
  tags:
  - "public"
spec:
  type: "documentation"
  lifecycle: "production"
  owner: "standardisering"
---
apiVersion: "backstage.io/v1alpha1"
kind: "Group"
metadata:
  name: "security_champion_retningslinjer-fagomrade-produktspesifikasjo"
  title: "Security Champion retningslinjer-fagomrade-produktspesifikasjon"
spec:
  type: "security_champion"
  parent: "it_security_champions"
  members:
  - "toreJohnsen"
  children:
  - "resource:retningslinjer-fagomrade-produktspesifikasjon"
---
apiVersion: "backstage.io/v1alpha1"
kind: "Resource"
metadata:
  name: "retningslinjer-fagomrade-produktspesifikasjon"
  links:
  - url: "https://github.com/kartverket/retningslinjer-fagomrade-produktspesifikasjon"
    title: "retningslinjer-fagomrade-produktspesifikasjon på GitHub"
spec:
  type: "repo"
  owner: "security_champion_retningslinjer-fagomrade-produktspesifikasjo"
  dependencyOf:
  - "component:retningslinjer-fagomrade-produktspesifikasjon"
